#this link is the about how to use docker-compose
#http://blog.csdn.net/yl_1314/article/details/53761049
#
version: '2'
services:
  App:
    image: nginx:root_index
    ports:
      - "8080:80"
    volumes:
      - /Users/xingkd:/data
    links:
      - One
      - Two
  One:
    image: nginx:web_server_1 
    ports:
      - "8081:80"
    volumes:
      - /Users/xingkd/program/balance/nginx1:/usr/share/nginx/html
  Two:
    image: nginx:web_server_1 
    ports:
      - "8082:80"
    volumes:
      - /Users/xingkd/program/balance/nginx2:/usr/share/nginx/html
